-- =============================================================================
-- B-Healthy — Article gate (read a teaser, give an email to read the rest)
-- Run ONCE in Supabase -> SQL Editor, project gngibdrjcnshyqkomkjs.
-- Idempotent: safe to re-run.
--
-- The point of doing this in the database rather than in the browser: until
-- now the full text of every article came back in one anonymous REST call, so
-- any gate built in JavaScript was a curtain, not a door. After this runs, the
-- rest of a gated article never leaves the server unless a valid token asks
-- for it.
--
-- Nothing here needs a new key in Vercel. The signing secret is generated by
-- Postgres, lives in a table no browser role can read, and is only ever
-- touched by the two security-definer functions below.
-- =============================================================================

-- pgcrypto may already be installed, and `if not exists` then ignores the
-- schema clause entirely -- so naming a fixed schema here breaks on any project
-- where it happens to live somewhere else. Call the functions plainly instead
-- and let the search path find them; every function below sets the same path.
set search_path = public, extensions;
create extension if not exists pgcrypto;

-- ------------------------------------------------------------- how much is free
-- Returns the opening of an article: as close to 20% of its length as the
-- blocks allow. Counting blocks instead would be meaningless — one article's
-- three blocks are a paragraph, another's are half the piece.
--
-- "Length" is characters of Thai body text, with a photo counted as 200 so an
-- article that opens with two images does not give them away for nothing.
--
-- Two deliberate consequences:
--   * The cut lands on whichever block boundary is NEAREST 20%, above or below.
--     Taking the last boundary under 20% starved long pieces; taking the first
--     one over it gave away up to half an article.
--   * A teaser never ends on a heading. A headline with nothing beneath it is
--     not a sample, it is a tease — so the cut walks back past it, and an
--     article whose opening is a heading plus one long list ends up locked from
--     the top. That is the intended outcome for a piece too short to sample.
create or replace function public.bh_teaser(p_body jsonb)
returns jsonb
language sql immutable set search_path = public as $$
  with src as (
    select case when jsonb_typeof(p_body) = 'array' then p_body else '[]'::jsonb end as body
  ),
  b as (
    select t.ord, t.value,
           (case t.value->>'type'
              when 'ul' then (
                select coalesce(sum(length(coalesce(i.value->>'th', i.value->>'en', ''))), 0)
                from jsonb_array_elements(
                       case when jsonb_typeof(t.value->'items') = 'array'
                            then t.value->'items' else '[]'::jsonb end) as i(value))
              when 'img' then 200
              else length(coalesce(t.value->>'th', t.value->>'en', ''))
            end)::numeric as w
    from src, jsonb_array_elements(src.body) with ordinality as t(value, ord)
  ),
  tot as (select coalesce(sum(w), 0) as total, count(*) as blocks from b),
  cuts as (
    select 0::bigint as n, 0::numeric as upto      -- giving nothing away is a candidate too
    union all
    select b.ord, sum(b.w) over (order by b.ord)
    from b
  ),
  pick as (
    select c.n from cuts c, tot
    where tot.total > 0
    order by abs(c.upto / tot.total - 0.20), c.n
    limit 1
  ),
  trimmed as (
    -- the largest cut at or below the chosen one that does not end on a heading
    select coalesce(max(g.n), 0) as n
    from generate_series(0, (select blocks from tot)) as g(n)
    where g.n <= (select n from pick)
      and (g.n = 0 or coalesce((select value->>'type' from b where b.ord = g.n), '') <> 'h2')
  )
  select coalesce(jsonb_agg(b.value order by b.ord), '[]'::jsonb)
  from b, trimmed
  where b.ord <= trimmed.n;
$$;

-- Left callable: it reads nothing, it only trims jsonb you already hold, and
-- being able to ask "what would this article show?" is worth more than the
-- nothing it hides.

-- ----------------------------------------------------------------- the teaser
-- Anonymous readers stop reading `packages` directly and read this instead.
-- A free article comes back whole; a gated one comes back with roughly its
-- first fifth (see bh_teaser above) and a flag the front end uses to draw the
-- email card.
-- Left without `security_invoker`, so it runs with the owner's rights. That is
-- the whole mechanism: the policy below shuts anonymous readers out of `post`
-- rows in `packages`, and this view is the one door back in — one that only
-- carries the teaser.
create or replace view public.posts_public as
select
  p.id,
  p.type,
  p.sort,
  p.updated_at,            -- the sitemap's lastmod; nothing secret about it
  case
    when coalesce((p.data->>'gated')::boolean, false) then
      (p.data - 'body') || jsonb_build_object(
        'gated', true,
        'body', public.bh_teaser(p.data->'body'))
    else p.data
  end as data
from public.packages p
where p.type = 'post' and p.status = 'published';

grant select on public.posts_public to anon, authenticated;

-- Close the door the view replaces. Retreats, workshops, membership tiers and
-- homepage topic photos stay public exactly as before — only articles move.
drop policy if exists "public read published packages" on public.packages;
create policy "public read published packages" on public.packages
  for select to anon using (status = 'published' and type <> 'post');

-- ------------------------------------------------------------- signing secret
create table if not exists public.app_secrets (
  name  text primary key,
  value bytea not null
);
alter table public.app_secrets enable row level security;
-- No policies on purpose: with RLS on and nothing granted, neither the
-- publishable key nor a signed-in staff account can read this table. Only the
-- security-definer functions below, which run as the owner, ever see it.

insert into public.app_secrets (name, value)
select 'article-gate', gen_random_bytes(32)
where not exists (select 1 from public.app_secrets where name = 'article-gate');

-- convert_to() is not decoration: pgcrypto offers hmac(bytea, bytea, text) and
-- hmac(text, text, text), and nothing in between. The key is bytea, so the
-- payload has to be bytea too or Postgres matches neither overload.
create or replace function public.bh_sign(p_payload text)
returns text
language sql stable security definer set search_path = public, extensions as $$
  select replace(
    encode(
      hmac(
        convert_to(p_payload, 'UTF8'),
        (select value from public.app_secrets where name = 'article-gate'),
        'sha256'),
      'base64'),
    E'\n', '');
$$;

-- bh_sign mints signatures, so handing it to the browser would hand over the
-- ability to forge an unlock. create function grants EXECUTE to PUBLIC by
-- default — take it straight back. The two functions below still reach it
-- because they run as the owner.
revoke all on function public.bh_sign(text) from public, anon, authenticated;

-- ------------------------------------------------------------------- unlock
-- Records the reader as a lead and returns a token good for 180 days.
-- The email is not verified — that is the deal: this is a lead gate, not a
-- login. It never hands out article text by itself.
create or replace function public.bh_unlock(p_email text, p_slug text default null)
returns text
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_email   text := lower(btrim(coalesce(p_email, '')));
  v_known   boolean;
  v_recent  int;
  v_payload text;
begin
  if char_length(v_email) > 200
     or v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'invalid email' using errcode = '22023';
  end if;

  select exists (select 1 from public.submissions where type = 'member' and email = v_email)
    into v_known;

  -- A returning reader who cleared their browser gets a fresh token without a
  -- duplicate lead. Only genuinely new emails can add rows, and a script
  -- trying to fill the table hits this ceiling long before anyone notices.
  if not v_known then
    select count(*) into v_recent from public.submissions
     where type = 'member' and created_at > now() - interval '1 hour';
    if v_recent >= 200 then
      raise exception 'too many signups right now' using errcode = '53400';
    end if;

    insert into public.submissions (type, email, subject, payload, status)
    values ('member', v_email, 'Article unlock',
            jsonb_build_object('slug', p_slug, 'source', 'article-gate'), 'new');
  end if;

  v_payload := replace(encode(convert_to(
      v_email || '|' || (extract(epoch from now() + interval '180 days'))::bigint::text,
      'UTF8'), 'base64'), E'\n', '');

  return v_payload || '.' || public.bh_sign(v_payload);
end $$;

-- --------------------------------------------------------------- the body
-- Returns the rest of the article, and only against a signature this database
-- produced. A bad, edited or expired token gets null, never a partial answer.
create or replace function public.bh_article_body(p_slug text, p_token text)
returns jsonb
language plpgsql stable security definer set search_path = public, extensions as $$
declare
  v_parts  text[];
  v_claims text[];
  v_exp    bigint;
begin
  if p_token is null or char_length(p_token) > 500 then return null; end if;

  v_parts := string_to_array(p_token, '.');     -- base64 has no '.', so this split is safe
  if coalesce(array_length(v_parts, 1), 0) <> 2 then return null; end if;
  if public.bh_sign(v_parts[1]) is distinct from v_parts[2] then return null; end if;

  begin
    v_claims := string_to_array(convert_from(decode(v_parts[1], 'base64'), 'UTF8'), '|');
  exception when others then
    return null;                                -- signature matched but the payload is unreadable
  end;

  -- Only reachable with a payload this database signed, so the expiry is
  -- always digits — but a cast that can raise would turn a bad token into a
  -- 500 instead of a polite no, and the whole point is that a no is quiet.
  if coalesce(v_claims[2], '') !~ '^[0-9]+$' then return null; end if;
  v_exp := v_claims[2]::bigint;
  if v_exp < extract(epoch from now()) then return null; end if;

  return (select p.data->'body' from public.packages p
           where p.id = p_slug and p.type = 'post' and p.status = 'published');
end $$;

revoke all on function public.bh_unlock(text, text)       from public;
revoke all on function public.bh_article_body(text, text) from public;
grant execute on function public.bh_unlock(text, text)       to anon, authenticated;
grant execute on function public.bh_article_body(text, text) to anon, authenticated;

-- --------------------------------------------------------------- measurement
-- The Analytics tab already counts page views; let it count the two steps of
-- the gate as well, so "how many saw the card" and "how many typed an email"
-- sit next to each other instead of being a guess.
alter table public.page_views drop constraint if exists page_views_kind_check;
alter table public.page_views add constraint page_views_kind_check
  check (kind in ('page', 'post', 'package', 'gate', 'unlock'));
